apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rpag
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rpag
    app.kubernetes.io/part-of: tkwch-fix-0075-0019-app
  name: devfile-sample-rpag
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rpag
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rpag
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0019-tenant/tkwch-fix-0075-0019-app/devfile-sample-rpag@sha256:ee5fe85e0ee6085e2168da2f54a5c63292cd3a2f70edb69a9c12e1fa6fc7a518
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
